version: '3'

services:

  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: customer
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3308:3306"
    expose:
      - "3308"

  app:
    build:
      context: ./CustomerApp
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql

