version: '3'

services:

  mysql:
    image: mysql:latest
    container_name: mysqldb
    environment:
      MYSQL_DATABASE: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3308:3306"
    expose:
      - "3308"

  app:
    build:
      context: ../UserApp
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
